services:
    postgresql:
        image: docker.io/bitnami/postgresql:17
        ports:
            - '5432:5432'
        environment:
            - POSTGRESQL_USERNAME=${DB_USERNAME}
            - POSTGRESQL_PASSWORD=${DB_PASSWORD}
            - POSTGRESQL_DATABASE=${DB_DATABASE}
        volumes:
            - 'postgresql_data:/bitnami/postgresql'
        container_name: ${APP_NAME}-postgresql
        networks:
            - app-network

    nginx:
        image: docker.io/bitnami/nginx:1.29
        ports:
            - '80:8080'
        container_name: ${APP_NAME}-nginx
        volumes:
            - ./:/app
            - ./docker/nginx/laravel.conf:/opt/bitnami/nginx/conf/server_blocks/laravel.conf:ro
        networks:
            - app-network

    php-fpm:
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        volumes:
            - ./:/app
            - ./docker/php/laravel.ini:/opt/bitnami/php/etc/conf.d/laravel.ini
        networks:
            - app-network
        container_name: ${APP_NAME}-php-fpm
        environment:
            - OPCACHE_ENABLE=${OPCACHE_ENABLE:-1}
            - OPCACHE_ENABLE_CLI=${OPCACHE_ENABLE_CLI:-1}

    php-cli:
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        volumes:
            - ./:/app
            - ./docker/php/laravel.ini:/opt/bitnami/php/etc/conf.d/laravel.ini
        networks:
            - app-network
        container_name: ${APP_NAME}-php-cli

    worker:
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        container_name: ${APP_NAME}-worker
        volumes:
            - ./:/app
            - ./docker/php/laravel.ini:/opt/bitnami/php/etc/conf.d/laravel.ini
            - ./docker/worker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
        networks:
            - app-network
        entrypoint: ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

volumes:
    postgresql_data:
        driver: local

networks:
    app-network:
