services:
    postgresql:
        image: docker.io/bitnami/postgresql:17
        ports:
            - '5432:5432'
        environment:
            - POSTGRESQL_USERNAME=${DB_USERNAME}
            - POSTGRESQL_PASSWORD=${DB_PASSWORD}
            - POSTGRESQL_DATABASE=${DB_DATABASE}
        volumes:
            - 'postgresql_data:/bitnami/postgresql'
        container_name: ${APP_NAME}-postgresql
        networks:
            - app-network

    nginx:
        image: docker.io/bitnami/nginx:1.29
        ports:
            - '80:8080'
        container_name: ${APP_NAME}-nginx
        volumes:
            - ./:/app
            - ./docker/nginx/laravel.conf:/opt/bitnami/nginx/conf/server_blocks/laravel.conf:ro
        networks:
            - app-network

    php-fpm:
        build:
            context: ./docker/php-fpm
            dockerfile: Dockerfile
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        container_name: ${APP_NAME}-php-fpm
        ports:
            - '9000:9000'
        environment:
            - UID=${UID:-1000}
            - GID=${GID:-1000}
        volumes:
            - ./:/app
        networks:
            - app-network

    supervisord:
        build:
            context: ./docker/supervisord
            dockerfile: Dockerfile
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        container_name: ${APP_NAME}-supervisord
        environment:
            UID: ${UID:-1000}
            GID: ${GID:-1000}
        volumes:
            - ./:/app
        networks:
            - app-network
        depends_on:
            - postgresql

volumes:
    postgresql_data:
        driver: local

networks:
    app-network:
