services:
    postgresql:
        image: docker.io/bitnami/postgresql:17
        ports:
            - '5432:5432'
        environment:
            - POSTGRESQL_USERNAME=${DB_USERNAME}
            - POSTGRESQL_PASSWORD=${DB_PASSWORD}
            - POSTGRESQL_DATABASE=${DB_DATABASE}
        volumes:
            - 'postgresql_data:/bitnami/postgresql'
        container_name: ${APP_NAME}-postgresql
        networks:
            - app-network

    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        container_name: ${APP_NAME}-nginx
        ports:
            - 80:8080
        volumes:
            - ./:/var/www/html
        networks:
            - app-network

    php-fpm:
        build:
            context: ./docker
            dockerfile: php-fpm/Dockerfile
        container_name: ${APP_NAME}-php-fpm
        environment:
            - UID=${UID:-1000}
            - GID=${GID:-1000}
        volumes:
            - ./:/var/www/html
        networks:
            - app-network

    php-cli:
        tty: true
        stdin_open: true
        build:
            context: ./docker
            dockerfile: php-cli/Dockerfile
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        container_name: ${APP_NAME}-php-cli
        environment:
            - UID=${UID:-1000}
            - GID=${GID:-1000}
        volumes:
            - ./:/var/www/html
        networks:
            - app-network

volumes:
    postgresql_data:
        driver: local

networks:
    app-network:
